version: '3'
services:
  mpls_container_1:
    build: ./mpls_container-1
    container_name: 'mpls_container_1'
    hostname: mpls_container_1
    privileged: true
    networks: 
      peer_1-2:
      peer_1-3:
      peer_4-a_1:
      peer_4-b_1:
  mpls_container_2:
    build: ./mpls_container-2
    container_name: 'mpls_container_2'
    hostname: mpls_container_2
    privileged: true
    networks:
      peer_1-2:
      peer_2-3:
      peer_2-4:
  mpls_container_3:
    build: ./mpls_container-3
    container_name: 'mpls_container_3'
    hostname: mpls_container_3
    privileged: true
    networks:
      peer_1-3:
      peer_2-3:
      peer_3-4:
  mpls_container_4:
    build: ./mpls_container-4
    container_name: 'mpls_container_4'
    hostname: mpls_container_4
    privileged: true
    networks:
      peer_2-4:
      peer_3-4:
      peer_4-a_2:
      peer_4-b_2:
  a_1:
    build: ./A_1
    container_name: 'a_1'
    hostname: a_1
    privileged: true
    networks:
      peer_4-a_1:
  a_2:
    build: ./A_2
    container_name: 'a_2'
    hostname: a_2
    privileged: true
    networks:
      peer_4-a_2:
  b_1:
    build: ./B_1
    hostname: b_1
    privileged: true
    container_name: 'b_1'
    networks:
      peer_4-b_1:
  b_2:
    build: ./B_2
    hostname: b_1
    privileged: true
    container_name: 'b_2'
    networks:
      peer_4-b_2:
networks:
  peer_1-2:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.1.2.0/24
  peer_1-3:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.1.3.0/24
  peer_3-4:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.3.4.0/24
  peer_2-4:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.2.4.0/24
  peer_2-3:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.2.3.0/24
  peer_4-a_1:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.1.98.0/24
  peer_4-a_2:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.1.99.0/24
  peer_4-b_1:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.4.98.0/24
  peer_4-b_2:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.4.99.0/24
